### ISSUE TITLE
Handle Interactive Comics

### ISSUE THREAD

**Issue by mamaral** [mamaral/xkcd-Open-Source#2]
Some comics aren't just images, they might be interactive pages or GIFs or some other stuff that we need to handle accordingly. First we need to investigate what these comics are and how to handle them. We should also use this area to keep track of any we come across.

**Comment by mamaral** [comment]
#1525 - Emojic :8ball:

**Comment by fergusean** [comment]
http://xkcd.com/1608/

only, this one's image URL is invalid, so it's also breaking the cacher.

**Comment by ghecho** [comment]
Also [#1663 - Garden](http://xkcd.com/1663/)

**Comment by Gaelan** [comment]
Click and Drag

**Comment by controversial** [comment]
Hmm?

**Comment by Gaelan** [comment]
Just adding to the list of non-working interactive xkcds.

**Comment by mamaral** [comment]
@Gaelan What number is that?

**Comment by controversial** [comment]
@mamaral 1110

**Comment by mamaral** [comment]
Current implementation will do for now.
