### ISSUE TITLE
How to do to make Cell in ComicListFlowLayout between horizontal and vertical gap?

### ISSUE THREAD

**Issue by xhzengAIB** [mamaral/xkcd-Open-Source#26]
@mamaral 
Hi！

I think inside the Cell to do clearance, this will happen asymmetric clearance, if within ComicListFlowLayout for horizontal or vertical gap will be more beautiful, 

Like this picture：
![fc2e13e4-eb78-4e6e-97e1-96f5554c6eba](https://cloud.githubusercontent.com/assets/1969908/9040173/dca60b14-3a32-11e5-9c6e-25713290f3d5.png)

**Comment by xhzengAIB** [comment]
@mamaral 
Should be there https://github.com/mamaral/xkcd-Open-Source/blob/master/Source/Layout/ComicListFlowLayout.m#L60 add DataSource Methods load horizontal or vertical gap

**Comment by mamaral** [comment]
Thanks for the feedback, although I'm personally partial to the current design. Any other feedback is always welcomed in the future!
