### ISSUE TITLE
After pod install and attempting to build, RLMObject.h file is not found

### ISSUE THREAD

**Issue by curdriceaurora** [mamaral/xkcd-Open-Source#31]

**Comment by yasirmturk** [comment]
Same issue here with 
Cocoapods 0.39.0 + Realm 0.95.2
Cocoapods 0.39.0 + Realm 0.96.2

It was working with 
Cocoapods 0.38.2 + Realm 0.95.2

**Comment by yasirmturk** [comment]
found the resolution if you using this header
`#import "RLMObject.h"`
change it to 
`#import <Realm/Realm.h>`

**Comment by mamaral** [comment]
Working on an update, this will be resolved shortly.

**Comment by mamaral** [comment]
Submitting v2.2 in a bit, lmk if you have any issues.
