### ISSUE TITLE
Zoom on iPad

### ISSUE THREAD

**Issue by luc-j-bourhis** [mamaral/xkcd-Open-Source#32]
Great app but all comics are always fully zoomed. As a result, the smallest of them look poorly on iPad's.

**Comment by Subject22** [comment]
I agree. Showing multiple comics on-screen at once would be better use of the space. Failing that, I'd prefer to see a smaller but less blurry comic in the middle of a white screen than a much-too-large comic which took up all the space.

**Comment by mamaral** [comment]
Cool, that could easily be done. I prefer the smaller/zoomed out version vs. multiple on screen at once.

**Comment by Subject22** [comment]
Actually, now that I think about it the main comic selection view literally is a view which displays many comics on screen at once. On an iPad Pro they're actually big enough to read quite comfortably.

**Comment by mamaral** [comment]
Given that many of them can be read from the comic screen and that I added the ability to view the alt text from the list directly, I'm going to close this now as its low on the priority list. Let me know if you have any concerns. Thanks!
