### ISSUE TITLE
Tap comic to view title text

### ISSUE THREAD

**Issue by Subject22** [mamaral/xkcd-Open-Source#34]
I always find myself searching for the little triple dot in the top right hand corner. What if tapping the comic brought up the title text as well? This would be especially handy on larger screen devices on which it is sometimes tricky to reach the top right hand corner of the device.

**Comment by mamaral** [comment]
This will be added in v2.2 I'm submitting shortly - I've moved the alt text button onto the bottom with the other buttons, and made the right nav button show a share sheet.
