### ISSUE TITLE
Quickly view comic title text on iPad Pro by tapping comic number icons

### ISSUE THREAD

**Issue by Subject22** [mamaral/xkcd-Open-Source#35]
The iPad Pro's screen is large enough that comics can be comfortably read from the main comic selection view (in fact, I often do this). It would be extra nice if I could tap the little comic number icons to bring up the title text for each comic (and also possibly mark that comic as read).

**Comment by mamaral** [comment]
This will be added in v2.2 I'm submitting shortly.
