### ISSUE TITLE
Swipe to move between comics

### ISSUE THREAD

**Issue by Subject22** [mamaral/xkcd-Open-Source#36]
I always find myself attempting to swipe left and right when viewing comics on my phone, before remembering that the forward/back buttons are in the toolbar. A swipe-to-change-comics feature could be useful.

**Comment by NguyenDytrich** [comment]
Will address this and open a pull request hopefully by tomorrow

**Comment by Bergenfrundt** [comment]
@NguyenDytrich created the pull request and it was merged, shouldn't this be closed now?

**Comment by mamaral** [comment]
Yup! Thanks folks
