### ISSUE TITLE
Unicode issue in title

### ISSUE THREAD

**Issue by controversial** [mamaral/xkcd-Open-Source#40]
It seems there's an incompatibility with encodings here

![img_3190](https://cloud.githubusercontent.com/assets/10377391/16732247/3e9fa1d4-474a-11e6-8134-160ae2631493.PNG)

**Comment by mamaral** [comment]
Indeed there is - I'll patch this ASAP. I still have a few outstanding fixes I want to push and get into a new version.

**Comment by controversial** [comment]
Ok, cool. FWIW, this issue makes it into the "share with Twitter" button as
well when it fills in the comic name

**Comment by mamaral** [comment]
Excellent, thanks for noticing this!

**Comment by controversial** [comment]
It's no problem. I like your app, so it's nice to contribute when I can 🙃

**Comment by mamaral** [comment]
Closing this as not fixing for now.
