### ISSUE TITLE
Feature: sharing via share sheet

### ISSUE THREAD

**Issue by cadeon** [mamaral/xkcd-Open-Source#41]
"Oooo, I need to send this one to <person>. I'll send it with <iMessage, email, other share-sheet method>"

Oh :-(

**Comment by controversial** [comment]
Yeah, this seems like a pretty big omission to me.

**Comment by mamaral** [comment]
@controversial Feel free to open a pull request :)

**Comment by controversial** [comment]
That probably won't happen soon as I know next to nothing about iOS, but
maybe I'll see if I can.

**Comment by mamaral** [comment]
This will be added in v2.2 I'm submitting shortly.

**Comment by controversial** [comment]
\o/

**Comment by cadeon** [comment]
Amazing! So much better!

**Comment by mamaral** [comment]
Awesome - @cadeon Feel free to leave a review - it helps out bigtime!

**Comment by cadeon** [comment]
Unfortunately I'm on iOS 10 - reviews are disabled on iOS 10 for some reason until it's released. Once it's out, though, I'll leave the best review ever. 

FYI the app seems to work fine on iOS 10.

**Comment by mamaral** [comment]
Great to know, and thank you!
