### ISSUE TITLE
Add button to view the comic's explanation on explainxkcd.com

### ISSUE THREAD

**Issue by lsapan** [mamaral/xkcd-Open-Source#43]
It would be great to modally present the explainxkcd page in a safari web view.

**Comment by mamaral** [comment]
Great idea!

**Comment by Pocketkid2** [comment]
If it's possible to pull the different sections of text I'd love to see a nice interface with the text loaded in, not just the website. I've alwys wanted this feature, I hope it gets implemented soon!

**Comment by mamaral** [comment]
Added in v2.4 of the app, now submitted to the App Store.
