### ISSUE TITLE
Bugs found in this app with the static analyzer Infer

### ISSUE THREAD

**Issue by dulmarod** [mamaral/xkcd-Open-Source#46]
Hi,

I attached here a list of bugs or warnings that I found while analyzing this app with Infer (www.fbinfer.com) a static analyzer. I ran the tool on this app to test it and to have a case study to show in a talk I'll be giving next week about it.  Do you think it's OK find for me to  show the issues found in may talk, and show snippets of code? 

https://www.dropbox.com/sh/5eku0yl6n27xwl4/AAArA0OzzVjkxwsSKNJ1v7d-a?dl=0

There are also bugs in file in the Pods, but the ones below are in the actual sources of the app:

**Bugs**
1. Source/Managers/Request Manager/RequestManager.m:74: warning: PARAMETER_NOT_NULL_CHECKED 
   Parameter handler is not checked for null, there could be a null pointer dereference: pointer handler could be null and is dereferenced at line 74, column 9
   1. if (!token) {
   2. NSError *error = [self errorWithMessage:kRequestManagerNilTokenErrorMessage];
   3. *_> *_ handler(error);
   4. return;
   5. }
2. Source/View Controllers/Comic/ComicViewController.h:27: warning: STRONG_DELEGATE_WARNING 
   Property or ivar delegate declared strong at line 27, column 1. In general delegates should be declared weak or assign
   1. @interface ComicViewController : UIViewController <UIScrollViewDelegate>
   2. 
   3. *_> *_@property (nonatomic) id<ComicViewControllerDelegate> delegate;
   4. 
   5. @property (nonatomic, strong) Comic *comic;
3. Source/View Controllers/Comic List/ComicListViewController.m:32: warning: REGISTERED_OBSERVER_BEING_DEALLOCATED 
   Object self is registered in a notification center but not being removed before deallocation at line 32, column 1. Consider removing the object from the notification center before its deallocation.
   1. @end
   2. 
   3. *_> *_@implementation ComicListViewController
4. Source/Managers/Data Manager/DataManager.m:22: warning: REGISTERED_OBSERVER_BEING_DEALLOCATED
   Object self is registered in a notification center but not being removed before deallocation at line 22, column 1. Consider removing the object from the notification center before its deallocation.
   1. @end
   2. 
   3. *_> *_@implementation DataManager

Thanks a lot,
Dulma

**Comment by mamaral** [comment]
Sure, you can use any available snippets/information you'd like. That seems like a really cool tool. Thank you for finding some issues! :)
