### ISSUE TITLE
Privacy

### ISSUE THREAD

**Issue by JohnMHarrisJr** [mamaral/xkcd-Open-Source#49]
Locking an issue like that is absurd. The issues with privacy on Apple software is as well documented as with Microsoft software. That is not relevant to the issue that I created, which you ignored the important part of. The important part of the issue was the tracking code itself, not with the tracking account.

**Comment by JohnMHarrisJr** [comment]
As this is a continuation of a 'locked' issue, I have closed it to avoid having useless open issues on your project.

**Comment by mamaral** [comment]
> Locking an issue like that is absurd.

The conversation was completely non-constructive. The fact that I've spent as much time as I already have on this responding to what I consider to be an extraordinarily absurd complaint blows my mind.

I'll repeat again, this project is a project that:

1. I made for free.
2. I make/charge no money for.
3. I have no ads.
4. I've open sourced the software for educational/demonstration purposes for ANYONE to learn from.

> The important part of the issue was the tracking code itself, not with the tracking account.

I'm not submitting a new version to the app store, I've essentially stopped development on this, so deleting the account is the only solution I could think of to _make you feel better_ and to avoid drama.

**Comment by JohnMHarrisJr** [comment]
The issue is tracking code itself, not your ability to view the data that is recorded.

I create software for free all the time, and I have never put an advertisement in software. That is a ridiculous way to make money from software. It invades the user's privacy and it makes your software look trashy.

Releasing this software under a free software license is great, and I'm glad that you decided to do that.

The way I would have handled this is very simple, charge some small amount for application binaries (say $1 or so).

**Comment by mamaral** [comment]
How does charging money solve this problem? I'm not complaining about not making money, I'm complaining that you're acting as if I'm some nefarious actor out to infringe on people's privacy. I'm just a guy who wanted to make something for people to use that they could enjoy.

I'm not submitting a new version to the store. With that in mind, what can I do to _stop receiving messages from you_ regarding this topic. I didn't start this project to be stressing out while I'm trying to enjoy my weekend.

**Comment by JohnMHarrisJr** [comment]
You do seem to be complaining about money, you keep mentioning that you're not making money from this. That is why I mentioned that as a possible solution for you.

I haven't insinuated that you're in any way 'evil'. I am just trying to help the users of your software, removing tracking code which invades their privacy.

**Comment by mamaral** [comment]
https://github.com/mamaral/xkcd-Open-Source/commit/6c9e207be8f3d085de610f465d8c8e6342686fae

One of these days I'll get around to figuring out how to submit the app to the store with other changes I previously made related to the app extension and entitlements, but all of the analytics code and SDKs have been removed. Enjoy your holidays.

**Comment by JohnMHarrisJr** [comment]
Thank you, and you too.
