### ISSUE TITLE
[Feature Request] Filter by Read/Unread

### ISSUE THREAD

**Issue by austin-guevara** [mamaral/xkcd-Open-Source#50]
Hey there,

Thanks for your work on such a terrific little project.

I would love to see the option to show only unread comics, this way you can make sure you literally have not missed a single XKDC comic created.

Thanks!

**Comment by mamaral** [comment]
Great idea!

**Comment by mamaral** [comment]
Added in v2.4 of the app, now submitted to the App Store.
