### ISSUE TITLE
Won’t launch

### ISSUE THREAD

**Issue by wallrodt** [mamaral/xkcd-Open-Source#77]
Brand new install on iPhone X with iOS 11.4. A small comic thumbnail appears for a second, then goes away, then a dialog box shows up with: “Oops! Am error occurred while loading this content. Please check your connection and try again” I am on WiFi. Uninstalling and reinstalling haven’t helped

**Comment by JuanCab** [comment]
I am getting this error also, I noticed the last three XKCD's hadn't loaded (as of today), so I wiped the cache in app, at which point it couldn't load ANYTHING .  I uninstalled and reinstalled, still doing this.

I revised the source and it appears at least on my mac that `https://xkcdos.app.sgnl24.com/latest-comic.php` has an expired security certificate, which is probably the issue.

**Comment by mamaral** [comment]
Should be resolved now - thanks everybody for the info!

**Comment by JuanCab** [comment]
Does not appear to be resolved for me...

**Comment by mamaral** [comment]
@JuanCab Try clearing the cache and/or reinstalling.

**Comment by JuanCab** [comment]
Yep, reinstall fixed it.  Thanks!
