### ISSUE TITLE
App will no longer download new content

### ISSUE THREAD

**Issue by mpeng3** [mamaral/xkcd-Open-Source#78]
Within the last week or so, the app has stopped downloading new comics. I tried uninstalling and reinstalling the app, and now it won’t load any at all - it just gets itself into an infinite loop of displaying the “Oops! An error occurred while loading this content...” message. Please fix this - I loved this app!

**Comment by Arc676** [comment]
I don't get the error, but I'm experiencing a similar issue. 2007 is the last comic downloaded.

**Comment by ghecho** [comment]
Exactly the same for me, I’m in iOS 12 beta 2 BTW. I thought it was because something broke in the beta. I can still receive notifications for new comics.

**Comment by SomeAspy** [comment]
I have this issue also. iOS 11.4.1 beta. Last loaded comic is #2007 and you still get notifications.

**Comment by juneeighteen** [comment]
+1 no new comics for me either, 2007 is the last one but notifications roll in

**Comment by controversial** [comment]
Same for me

**Comment by Arc676** [comment]
I’d like to report that the app just downloaded all the new comics (2008-2012).

**Comment by j-f1** [comment]
This seems to be fixed now.
