### ISSUE TITLE
Doesn’t load comics anymore

### ISSUE THREAD

**Issue by JuanCab** [mamaral/xkcd-Open-Source#91]
Didn't open app for a week, not it won't load new comics.  Cleared cache, now reports an error "Oops, an error occurred while loading content."  Any ideas?

**Comment by PeterSommerlad** [comment]
happened to me now. any ideas.  delete and reinstall didn't help.

**Comment by JuanCab** [comment]
Funny thing, after a few years of everything working right, it started failing again (only noticed it because of PeterSommerlad comment).  Yeah, can't get it to work any more.

**Comment by nrnrnr** [comment]
I’m seeing this issue as well. The last one to load was number 2641.

**Comment by fergusean** [comment]
Apologies all.  Server issue.  Should be all set now.
