### ISSUE TITLE
Has ceased to update after XKCD 2915

### ISSUE THREAD

**Issue by JuanCab** [mamaral/xkcd-Open-Source#97]
The app no longer will update after the release of xkcd #2916 which is not a standard image but an animation called "Machine".  App might need an update to deal with it.

**Comment by fergusean** [comment]
ahh, I moved the backend to a new server - I tested it, but not well enough apparently.  I see the issue, working on a fix now!

**Comment by fergusean** [comment]
All set - thanks for reporting!

**Comment by JuanCab** [comment]
Thanks for the quick fix!
